spring:
  application:
    name: quietup-server
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never